## Setup

You will need to make a copy of this notebook in your Google Drive before you can edit the homework files. You can do so with **File &rarr; Save a copy in Drive**.

In [ ]:
#@title mount your Google Drive
#@markdown Your work will be stored in a folder called `cs285_f2023` by default to prevent Colab instance timeouts from deleting your edits.

import os
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

In [3]:
#@title set up mount symlink

DRIVE_PATH = '/content/gdrive/My\ Drive/cs285_f2023'
DRIVE_PYTHON_PATH = DRIVE_PATH.replace('\\', '')
if not os.path.exists(DRIVE_PYTHON_PATH):
  %mkdir $DRIVE_PATH

## the space in `My Drive` causes some issues,
## make a symlink to avoid this
SYM_PATH = '/content/cs285_f2023'
if not os.path.exists(SYM_PATH):
  !ln -s $DRIVE_PATH $SYM_PATH

In [4]:
#@title apt install requirements

#@markdown Run each section with Shift+Enter

#@markdown Double-click on section headers to show code.

!apt update
!apt install -y --no-install-recommends \
        build-essential \
        curl \
        git \
        gnupg2 \
        make \
        cmake \
        ffmpeg \
        swig \
        libz-dev \
        unzip \
        zlib1g-dev \
        libglfw3 \
        libglfw3-dev \
        libxrandr2 \
        libxinerama-dev \
        libxi6 \
        libxcursor-dev \
        libgl1-mesa-dev \
        libgl1-mesa-glx \
        libglew-dev \
        libosmesa6-dev \
        lsb-release \
        ack-grep \
        patchelf \
        wget \
        xpra \
        xserver-xorg-dev \
        ffmpeg
!apt-get install python-opengl -y
!apt install xvfb -y

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
16 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
N

In [5]:

#@title clone homework repo

%cd $SYM_PATH
!git clone https://github.com/berkeleydeeprlcourse/homework_fall2023.git
%cd hw1
%pip install -r requirements_colab.txt
%pip install -e .

/content/gdrive/My Drive/cs285_f2023
/content/gdrive/My Drive/cs285_f2023/hw1
Obtaining file:///content/gdrive/My%20Drive/cs285_f2023/hw1
  Preparing metadata (setup.py) ... done
  Attempting uninstall: cs285
    Found existing installation: cs285 0.1.0
    Uninstalling cs285-0.1.0:
      Successfully uninstalled cs285-0.1.0
  Running setup.py develop for cs285


In [6]:
#@title set up virtual display

from pyvirtualdisplay import Display

display = Display(visible=0, size=(1400, 900))
display.start()

In [66]:
import os

In [16]:
#@title test virtual display

#@markdown If you see a video of a four-legged ant fumbling about, setup is complete!

import gym
from cs285.infrastructure.colab_utils import (
    wrap_env,
    show_video
)

env = wrap_env(gym.make("Ant-v4", render_mode='rgb_array'))

observation = env.reset()
for i in range(100):
    env.render()
    obs, rew, term, _ = env.step(env.action_space.sample() )
    if term:
        print("term")
        break;

env.close()
print('Loading video...')
show_video()

C:\Users\82107\anaconda3\envs\rl\lib\site-packages\gym\core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
C:\Users\82107\anaconda3\envs\rl\lib\site-packages\gym\wrappers\step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
C:\Users\82107\anaconda3\envs\rl\lib\site-packages\gym\wrappers\record_video.py:78: UserWarning: WARN: Overwriting existing videos at C:\content\video folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
C:\Users\82107\anaconda3\envs\rl\lib\site-packages\gym\utils\passive_env_checker.py:241: DeprecationWarnin

Loading video...


## Editing Code

To edit code, click the folder icon on the left menu. Navigate to the corresponding file (`cs285_f2020/...`). Double click a file to open an editor. You will need to edit code in the following files:
```markdown
* cs285/policies/MLP_policy.py
* cs285/infrastructure/utils.py
* cs285/scripts/run_hw1.py
```

## Run Behavior Cloning (Problem 1)

Note that there is a timeout of about ~12 hours with Colab while it is active (and less if you close your browser window). We sync your edits to Google Drive so that you won't lose your work in the event of an instance timeout, but you will need to re-mount your Google Drive and re-install packages with every new instance.

In [8]:
cd ../..

C:\Users\82107\OneDrive - 연세대학교 (Yonsei University)\AI\RL\rl_berkeley\hw1


In [9]:
#@title imports

import time
import os
from cs285.scripts.run_hw1 import run_training_loop

%load_ext autoreload
%autoreload 2

C:\Users\82107\anaconda3\envs\rl\lib\site-packages\IPython\extensions\autoreload.py:121: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload


In [10]:
#@title runtime arguments

class Args:

  def __getitem__(self, key):
    return getattr(self, key)

  def __setitem__(self, key, val):
    setattr(self, key, val)

  #@markdown expert data
  expert_policy_file = 'cs285/policies/experts/Ant.pkl' #@param
  expert_data = 'cs285/expert_data/expert_data_Ant-v4.pkl' #@param
  env_name = 'Ant-v4' #@param ['Ant-v4', 'Walker2d-v4', 'HalfCheetah-v4', 'Hopper-v4']
  exp_name = 'bc_ant' #@param
  do_dagger = True #@param {type: "boolean"}
  ep_len = 1000 #@param {type: "integer"}
  save_params = False #@param {type: "boolean"}

  num_agent_train_steps_per_iter = 1000 #@param {type: "integer"})
  n_iter = 5 #@param {type: "integer"})

  #@markdown batches & buffers
  batch_size_initial = 2000 #@param {type: "integer"})
  batch_size = 1000 #@param {type: "integer"})
  eval_batch_size = 1000 #@param {type: "integer"}
  train_batch_size = 100 #@param {type: "integer"}
  max_replay_buffer_size = 1000000 #@param {type: "integer"}

  #@markdown network
  n_layers = 2 #@param {type: "integer"}
  size = 64 #@param {type: "integer"}
  learning_rate = 5e-3 #@param {type: "number"}

  #@markdown logging
  video_log_freq = 5 #@param {type: "integer"}
  scalar_log_freq = 1 #@param {type: "integer"}

  #@markdown gpu & run-time settings
  no_gpu = False #@param {type: "boolean"}
  which_gpu = 0 #@param {type: "integer"}
  seed = 1 #@param {type: "integer"}

args = Args()


In [11]:
#@title create directory for logging

if args.do_dagger:
    logdir_prefix = 'q2_'  # The autograder uses the prefix `q2_`
    assert args.n_iter>1, ('DAgger needs more than 1 iteration (n_iter>1) of training, to iteratively query the expert and train (after 1st warmstarting from behavior cloning).')
else:
    logdir_prefix = 'q1_'  # The autograder uses the prefix `q1_`
    assert args.n_iter==1, ('Vanilla behavior cloning collects expert data just once (n_iter=1)')

data_path ='/content/cs285_f2023/hw1/data'
if not (os.path.exists(data_path)):
    os.makedirs(data_path)
logdir = logdir_prefix + args.exp_name + '_' + args.env_name + \
         '_' + time.strftime("%d-%m-%Y_%H-%M-%S")
logdir = os.path.join(data_path, logdir)
args['logdir'] = logdir
if not(os.path.exists(logdir)):
    os.makedirs(logdir)

In [25]:
## run training
print(args.logdir)
run_training_loop(args)

/content/cs285_f2023/hw1/data\q2_bc_ant_Ant-v4_15-02-2024_10-01-36
########################
logging outputs to  /content/cs285_f2023/hw1/data\q2_bc_ant_Ant-v4_15-02-2024_10-01-36
########################
GPU not detected. Defaulting to CPU.
Loading expert policy from... cs285/policies/experts/Ant.pkl
obs (1, 111) (1, 111)
Done restoring expert policy...


********** Iteration 0 ************


Training agent using sampled data from replay buffer...

Beginning logging procedure...



AttributeError: 'Tensor' object has no attribute 'to_numpy'

In [18]:
import numpy as np
import torch
a = np.array([1,3,4])
a= torch.tensor([1,2,34])

a= torch.tensor([1])
if a:
    print('t')

t


In [24]:
import pickle
import os
import time
import gym

import numpy as np
import torch

from cs285.infrastructure import pytorch_util as ptu
from cs285.infrastructure import utils
from cs285.infrastructure.logger import Logger
from cs285.infrastructure.replay_buffer import ReplayBuffer
from cs285.policies.MLP_policy import MLPPolicySL
from cs285.policies.loaded_gaussian_policy import LoadedGaussianPolicy


In [28]:
params = args
logger = Logger(params['logdir'])

# Set random seeds
seed = params['seed']
np.random.seed(seed)
torch.manual_seed(seed)
ptu.init_gpu(
    use_gpu=not params['no_gpu'],
    gpu_id=params['which_gpu']
)

# Set logger attributes
log_video = True
log_metrics = True

#############
## ENV
#############

# Make the gym environment
env = gym.make(params['env_name'], render_mode=None)
env.reset(seed=seed)

########################
logging outputs to  /content/cs285_f2023/hw1/data\q2_bc_ant_Ant-v4_14-02-2024_14-19-51
########################
GPU not detected. Defaulting to CPU.


array([ 6.78831923e-01,  9.97505386e-01, -3.44487459e-02, -1.40369243e-02,
        5.99937848e-02, -1.81601727e-02,  9.91873753e-03, -9.44881774e-02,
        5.07026217e-02,  7.62866264e-03, -3.40536567e-02,  5.76857407e-02,
       -3.93610341e-02,  5.98846213e-02,  3.97221075e-03, -2.92456751e-02,
       -7.81908462e-02, -2.57192241e-02,  8.14218052e-04, -2.75602905e-02,
        1.29406381e-01,  1.00672432e-01, -2.71116248e-01, -1.88901325e-01,
       -1.74772092e-02, -4.22190412e-02,  2.13642997e-02])

In [72]:
a = torch.distributions.normal.Normal(0,1)

In [120]:
mean = torch.tensor([0.1], requires_grad = True)
std = torch.tensor([0.01], requires_grad = True)

In [121]:
mean2 = mean * 2
std2 = std * 5

In [122]:
y = torch.distributions.Normal(mean2,std2)

In [148]:
torch.nn.MSELoss()

MSELoss()

In [123]:
loss= torch.norm(y.rsample((5,)))
loss.backward()

In [140]:
a = torch.distributions.Distribution(3,3)

In [150]:
a = torch.distributions.Normal(torch.rand(3),torch.rand(3),)

In [164]:
ac = env.action_space.sample()

In [168]:
ac.shape

(8,)

In [192]:
ac

array([ 0.44190183,  0.04700914, -0.22512011,  0.86936665,  0.9922781 ,
       -0.58736837,  0.9109502 , -0.5419683 ], dtype=float32)

In [200]:
a = {}

In [202]:
b= a.copy()

In [203]:
b[0] = 1

In [206]:
env.reset()

<TimeLimit<OrderEnforcing<StepAPICompatibility<PassiveEnvChecker<AntEnv<Ant-v4>>>>>>

In [199]:
ac[idx]

array([-0.22512011,  0.9922781 ,  0.86936665,  0.44190183,  0.9109502 ],
      dtype=float32)

In [196]:
idx = np.random.permutation(range(len(ac)))[:5]

In [194]:
np.random.permutation([ac,ac])

array([[ 0.44190183,  0.04700914, -0.22512011,  0.86936665,  0.9922781 ,
        -0.58736837,  0.9109502 , -0.5419683 ],
       [ 0.44190183,  0.04700914, -0.22512011,  0.86936665,  0.9922781 ,
        -0.58736837,  0.9109502 , -0.5419683 ]], dtype=float32)

In [ ]:
env.env.step

In [177]:
args.batch_size

1000

In [174]:
env.step(ac)

[autoreload of cs285.policies.MLP_policy failed: Traceback (most recent call last):
  File "C:\Users\82107\anaconda3\envs\rl\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\82107\anaconda3\envs\rl\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Users\82107\anaconda3\envs\rl\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\82107\anaconda3\envs\rl\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\82107\OneDrive - 연세대학교 (Yonsei University)\AI\RL\rl_berkeley\hw1\cs285\policies\MLP_policy.py", line 28, in <module>
    size: intt
NameError: name 

(array([ 8.66368987e-01,  9.95898869e-01, -5.42133901e-02,  7.23902541e-02,
        -2.44978760e-03, -3.34433828e-02,  4.97823803e-01,  2.39464590e-01,
        -4.74513351e-01,  1.98295057e-01, -4.59407572e-01,  2.01202545e-02,
         4.42677491e-01,  3.40873507e-02,  3.75610472e-01,  4.16122166e-01,
         4.30761872e-01,  4.58538007e-01, -2.34957292e+00, -1.56634470e+00,
         1.27344337e+01,  7.37742429e+00, -1.15680202e+01,  6.61862209e+00,
        -1.23302398e+01,  3.38916037e+00,  8.17130121e+00]),
 -0.6175389468994794,
 False,
 {'reward_forward': 0.11103199121087204,
  'reward_ctrl': -1.7285709381103516,
  'reward_survive': 1.0,
  'x_position': 0.07621961445894765,
  'y_position': -0.03533660395271272,
  'distance_from_origin': 0.08401253006058974,
  'x_velocity': 0.11103199121087204,
  'y_velocity': 0.18261195826922982,
  'forward_reward': 0.11103199121087204})

In [158]:
env.env.action_space.

TypeError: 'Box' object is not callable

In [153]:
a.rsample()

tensor([1.3095, 1.0949, 0.1280])

In [138]:
a = torch.distributions.Distribution.Normal(torch.tensor([0,1,2]),torch.tensor([1,1,0.1]))

AttributeError: type object 'Distribution' has no attribute 'Normal'

In [124]:
mean.grad

tensor([4.4413])

In [35]:
env.model.opt.timestep

0.01

In [48]:
env.action_space

Box(-1.0, 1.0, (8,), float32)

In [50]:
env.action_space.sample()

array([-0.43371233,  0.00774042, -0.16439505,  0.8698357 ,  0.8190848 ,
        0.8375272 , -0.92241544,  0.8149823 ], dtype=float32)

In [64]:
env.observation_space.sample()

array([-0.52601908, -1.23961575,  0.59275587, -1.47721173, -1.76122203,
        0.45753629,  1.14984172,  1.47327078,  0.86345376, -0.06271851,
        1.48872233,  0.48975196,  0.65799949,  0.98758801, -1.62558197,
        0.87994001, -0.78727849,  0.1449918 ,  0.63563811, -0.10243453,
       -1.30519294,  0.41365547, -0.89110681,  0.6719251 ,  0.27196256,
       -0.19247483,  1.19640213])

In [38]:
env.metadata

{'render_modes': ['human',
  'rgb_array',
  'depth_array',
  'single_rgb_array',
  'single_depth_array'],
 'render_fps': 20}

In [37]:
env.env.metadata

{'render_modes': ['human',
  'rgb_array',
  'depth_array',
  'single_rgb_array',
  'single_depth_array'],
 'render_fps': 20}

In [36]:
#@markdown You can visualize your runs with tensorboard from within the notebook

%load_ext tensorboard
%tensorboard --logdir /content/cs285_f2023/hw1/data

## Running DAgger (Problem 2)
Modify the settings above:
1. check the `do_dagger` box
2. set `n_iters` to `10`
3. set `exp_name` to `dagger_{env_name}`
and then rerun the code.